export const graphColumns = [
	{ value: "TS1", label: "TS1" },
	{ value: "TS2", label: "TS2" },
	{ value: "TS3", label: "TS3" },
	{ value: "TS4", label: "TS4" },
	{ value: "TS5", label: "TS5" },
	{ value: "TS6", label: "TS6" },
	{ value: "TS7", label: "TS7" },
	{ value: "TS8", label: "TS8" },
	{ value: "TS9", label: "TS9" },
	{ value: "PT", label: "PT" },
	{ value: "PTO", label: "PTO" },
	{ value: "PTUV", label: "PTUV" },
	{ value: "PPT", label: "PPT" },
	{ value: "PTO2", label: "PTO2" },
	{ value: "komp", label: "komp" },
	{ value: "kvyk", label: "kvyk" },
	{ value: "run", label: "run" },
	{ value: "reg", label: "reg" },
	{ value: "vjedn", label: "vjedn" },
	{ value: "dzto", label: "dzto" },
	{ value: "dztuv", label: "dztuv" },
	{ value: "tstat", label: "tstat" },
	{ value: "hdo", label: "hdo" },
	{ value: "obd", label: "obd" },
	{ value: "RPT", label: "RPT" },
	{ value: "Prtk", label: "Prtk" },
	{ value: "TpnVk", label: "TpnVk" },
	{ value: "chyba", label: "chyba" },
];

export const chartConfig = {
	TS1: { label: "TS1", color: "#0800ff", unit: "°C" },
	TS2: { label: "TS2", color: "#00d0ff", unit: "°C" },
	TS3: { label: "TS3", color: "#9500ff", unit: "°C" },
	TS4: { label: "TS4", color: "#6e4900", unit: "°C" },
	TS5: { label: "TS5", color: "#ff8000", unit: "°C" },
	TS6: { label: "TS6", color: "#1fa32c", unit: "°C" },
	TS7: { label: "TS7", color: "#e817ff", unit: "°C" },
	TS8: { label: "TS8", color: "#17ff49", unit: "°C" },
	TS9: { label: "TS9", color: "#ec6263", unit: "°C" },
	PT: { label: "PT", color: "#dbc77d", unit: "°C" },
	PTO: { label: "PTO", color: "#d4d4d4", unit: "°C" },
	PTUV: { label: "PTUV", color: "#996e00", unit: "°C" },
	PPT: { label: "PPT", color: "#deca14", unit: "°C" },
	PTO2: { label: "PTO2", color: "#15cfc2", unit: "°C" },
	komp: { label: "komp", color: "#4a8f00", unit: "" },
	kvyk: { label: "kvyk", color: "#ff0000", unit: "%" },
	run: { label: "run", color: "#9500ff", unit: "" },
	reg: { label: "reg", color: "#ffffff", unit: "" },
	vjedn: { label: "vjedn", color: "#6e4900", unit: "" },
	dzto: { label: "dzto", color: "#00ffdd", unit: "" },
	dztuv: { label: "dztuv", color: "#0022ff", unit: "" },
	tstat: { label: "tstat", color: "#ff7700", unit: "" },
	hdo: { label: "hdo", color: "#9000ff", unit: "" },
	obd: { label: "obd", color: "#bfbfbf", unit: "" },
	RPT: { label: "RPT", color: "#ede90c", unit: "" },
	Prtk: { label: "Prtk", color: "#1493e3", unit: "" },
	TpnVk: { label: "TpnVk", color: "#a10000", unit: "" },
	chyba: { label: "chyba", color: "#ff0000", unit: "" },
} as const;

export const chartColors = {
	light: {
		axisColor: "#292929",
		gridColor: "#858585",
	},
	dark: {
		axisColor: "#e0e0e0",
		gridColor: "#555555",
	},
} as const;
